# Generated by Django 4.0.4 on 2022-04-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=24)),
                ('Apellidos', models.CharField(max_length=24)),
                ('Fecha_de_nacimiento', models.DateField()),
                ('Genero', models.CharField(max_length=9)),
                ('Numero_de_contacto', models.PositiveIntegerField()),
                ('Email', models.EmailField(default='email@test.com', max_length=254)),
            ],
        ),
    ]
