# Generated by Django 4.0.4 on 2022-04-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_contactos_remove_cliente_numero_de_contacto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Email',
            new_name='Correo_electronico',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Numero_de_contacto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Numero_de_contacto',
            field=models.PositiveIntegerField(default=9999999999),
        ),
        migrations.DeleteModel(
            name='contactos',
        ),
    ]
